[workspace]
authors = ["Fredrick Eisele <fred.eisele@vanderbilt.edu>"]
name = "pixi-build-example"
version = "0.1.0"

channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies] 
python_rich_mgr = { path = "pkgs/python_rich_mgr" }
cpp_math = { path = "pkgs/cpp_math" }
python_rich = { path = "pkgs/python_rich" }

[tasks] 
start = "rich-example-main"
