[build-system] 
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = ["rich"]                              
name = "python_rich_mgr"
requires-python = ">= 3.11"
scripts = { rich-example-main = "python_rich_mgr:main" } 
version = "0.1.0"

