

[dependencies] 
python_rich = { path = "." }
cpp_math = { path = "pkgs/cpp_math"}

[tasks] 
start = "rich-example-main"

[package] 
name = "python_rich"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"

[package.run-dependencies] 
rich = "13.9.*"
