[project]
dependencies = ["rich"]                              
name = "python_rich"
requires-python = ">= 3.11"
# scripts = { rich-example-main = "python_rich_mgr:main" } 
version = "0.1.0"

[build-system] 
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi]

[tool.pixi.dependencies] 
python_rich = { path = "." }
cpp_math = { path = "pkgs/cpp_math"}

[tool.pixi.package] 
name = "python_rich"
version = "0.1.0"

[tool.pixi.package.build] 
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tool.pixi.package.host-dependencies] 
hatchling = "==1.26.3"

[tool.pixi.package.run-dependencies] 
rich = "13.9.*"